"""Generates Tcl scripts for OpenSTA execution."""
from pathlib import Path
from typing import Optional


class TCLGenerator:
    """Builds a complete OpenSTA Tcl script from a benchmark manifest and analysis config."""

    HEADER = """\
# OpenSTA Tcl script — auto-generated by sta-choa
# Do not edit manually.
"""

    def generate(
        self,
        liberty: str,
        verilog: str,
        sdc: str,
        top_module: str,
        sdf: Optional[str] = None,
        spef: Optional[str] = None,
        path_count: int = 50,
        path_delay: str = "max",
        report_path: str = "/tmp/sta_report.txt",
        slack_margin: float = 0.0,
        extra_cmds: Optional[list] = None,
    ) -> str:
        lines = [self.HEADER]

        # Load timing libraries
        lines.append(f'read_liberty -min "{liberty}"')
        lines.append(f'read_liberty -max "{liberty}"')

        # Load netlist and link
        lines.append(f'read_verilog "{verilog}"')
        lines.append(f'link_design {top_module}')

        # Load constraints
        lines.append(f'read_sdc "{sdc}"')

        # Optional SDF annotation
        if sdf:
            lines.append(f'read_sdf "{sdf}"')

        # Optional parasitic annotation
        if spef:
            lines.append(f'read_spef "{spef}"')

        # Apply slack margin as clock uncertainty adjustment if nonzero
        if abs(slack_margin) > 1e-6:
            lines.append(f'set_clock_uncertainty {slack_margin:.4f} [all_clocks]')

        # Timing checks
        lines.append('')
        lines.append('# Run timing analysis')
        lines.append(f'report_checks -path_delay {path_delay} -fields {{slew capacitance input_pins net}} -digits 4 -path_count {path_count} > "{report_path}"')
        lines.append(f'report_wns >> "{report_path}"')
        lines.append(f'report_tns >> "{report_path}"')
        lines.append(f'report_check_types -max_slew -max_capacitance -max_fanout -violators >> "{report_path}"')
        lines.append(f'report_clock_skew >> "{report_path}"')

        if extra_cmds:
            lines.extend(extra_cmds)

        lines.append('exit')
        return '\n'.join(lines) + '\n'

    def generate_incremental(
        self,
        report_path: str,
        path_count: int = 20,
        path_delay: str = "max",
    ) -> str:
        """Tcl fragment for re-running timing after ECO without reloading design."""
        lines = [
            '# Incremental re-analysis',
            f'report_checks -path_delay {path_delay} -path_count {path_count} > "{report_path}"',
            f'report_wns >> "{report_path}"',
            f'report_tns >> "{report_path}"',
        ]
        return '\n'.join(lines) + '\n'

    def write(self, content: str, path: str) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        return p
